#!/bin/bash

PROG=$(PATH=${PATH//\/var\/lib\/lunar\/compilers/} type -p $(basename $0))

if [[ -n "$LUNAR_DEBUG" ]] ; then
  echo "++ $CXX_EXT $PROG $CCOPT \"$@\"" >&2
fi

exec $CXX_EXT $PROG $CCOPT "$@"

